export const API = {
  BAND_SWIPER: `/MainBandData.json`,
  BIG_BANNER: `/BigBannerData.json`,
  GOOB_NEWS: `/GoobNewsData.json`,
  GOOB_STAR: `/GoobStarData.json`,
  GOOB_TUBE: `/GoobTubeData.json`,
  NAV: `/NavListData.json`,
  LISTITEM: `/ListItemAllData.json`,
  LOGINPOST: `/login`,
  DETAIL: `/DetailData.json`,
  CART_SWIPER: `/CartSwiper.json`,
  DELIVERY_SWIPER: `/DeliverySwiper.json`,
  MENU_CHIP: `/MenuChipData.json`,
  POPULAR_CHIP: `/PopularChipData.json`,
  CART_PRODUCT: `/CartProductData.json`,
  CART_INFO: `/CartInfoData.json`,
  JOIN_POST: `/join`,
};
